name: libelfRobot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
      - name: Waiting for reviewers
        run: echo Waiting for the development workflow reviewers...
  
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
    needs: deploy-dev
    steps:
      - name: Waiting for homologation stage
        run: echo Waiting for the homologation workflow reviewers...
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: deploy-hmg
    steps:
      - name: Waiting for begin in production
        run: echo Waiting for the production workflow reviewers...
  

      
